import assert from 'node:assert/strict';
import { readFile } from 'node:fs/promises';
import { test } from 'node:test';
import { createCodeRuntime } from '../runtime/code-runtime.mjs';
import { truncateText } from '../../nanocodex-tools/runtime/code-output.mjs';

// Generated by executing pinned Codex's actual V8 helper functions and Rust
// truncation implementation, not by this JavaScript port.
const oracle = JSON.parse(await readFile(new URL('../../../crates/nanocodex-tools/src/code_mode/native-behavior.json', import.meta.url)));
for (const evaluator of ['native', 'quickjs', 'worker']) {
  test(`${evaluator} matches upstream helper oracle`, async () => {
    let evaluate;
    if (evaluator === 'quickjs') {
      const { default: variant } = await import('@jitl/quickjs-wasmfile-release-asyncify');
      const { newQuickJSAsyncWASMModuleFromVariant } = await import('quickjs-emscripten-core');
      const { createQuickJsEvaluator } = await import('../runtime/quickjs-evaluator.mjs');
      evaluate = createQuickJsEvaluator(await newQuickJSAsyncWASMModuleFromVariant(variant));
    } else if (evaluator === 'worker') {
      const { NodeWebWorker } = await import('./support/node-web-worker.mjs');
      const { createWorkerEvaluator } = await import('../runtime/worker-evaluator.mjs');
      evaluate = createWorkerEvaluator({ createWorker: () => new NodeWebWorker(new URL('../runtime/code-evaluator.worker.mjs', import.meta.url)) });
    }
    const runtime = createCodeRuntime({}, { evaluate });
    try {
      for (const example of oracle.helpers) {
        const result = JSON.parse(await runtime.executeCode(`${example.kind}(${example.expression});`));
        if ('error' in example.result) {
          assert.equal(result.success, false, example.expression);
          assert.ok(result.output.includes(example.result.error), `${example.expression}: ${result.output}`);
        } else {
          assert.equal(result.success, true, example.expression);
          assert.deepEqual(result.output.at(-1), example.result.item, example.expression);
        }
      }
    } finally { runtime.reset(); }
  });
}
for (const example of oracle.truncations) test(`upstream truncation ${JSON.stringify(example)}`, () => {
  assert.equal(truncateText(example.text, example.tokens), example.result);
});
