local NS={}
assert(loadfile('addon/Transport.lua'))('Nanocodex',NS)
local T=NS.Transport
assert(T.CRC('123456789')==10673)
local function bad(v) assert(not v) end
local a,b=T.New(123),T.New(123)
local delivered=0 b.deliver=function(p) assert(p=='hello') delivered=delivered+1 end
assert(a:Send('hello')==1) bad(a:Send('busy'))
assert(b:Receive(a:Packet())) assert(b:Receive(a:Packet())) assert(delivered==1)
assert(a:Receive(b:Packet())) assert(a.pending==nil)
bad(b:Receive(T.Encode(124,2,0,'hello',true)))
bad(b:Receive(T.Encode(123,3,0,'hello',true)))
bad(b:Receive(T.Encode(123,1,0,'different',true)))
bad(b:Receive(T.Encode(123,2,1,'hello',true)))
local packet=T.Encode(123,2,0,'hello',true)
for i=1,#packet do
 local corrupt=packet:sub(1,i-1)..string.char((packet:byte(i)+1)%256)..packet:sub(i+1)
 bad(T.Decode(corrupt))
end
local now,count=0,0
local k=T.NewKeys(function(s) assert(s==packet) count=count+1 return true end,function() return now end)
local function feed(p)
 k:Key('F21')
 for i=1,#p do local n=p:byte(i) k:Key('F'..(13+math.floor(n/64))) k:Key('F'..(13+math.floor(n/8)%8)) k:Key('F'..(13+n%8)) end
 return k:Key('F22')
end
assert(feed(packet)) assert(count==1)
k:Key('F21') k:Key('F20') k:Key('F20') k:Key('F20') assert(k.buffer==nil)
k:Key('F21') k:Key('F13') now=3 k:Key('F22') assert(count==1)
k:Key('F21') for _=1,336 do k:Key('F13') end assert(k.buffer==nil)
assert(not k:Key('W'))
local accepted=0
local strict=T.NewKeys(function(s) if T.Decode(s) then accepted=accepted+1 end end,function() return now end)
local stream={'F21'}
for i=1,#packet do local n=packet:byte(i) stream[#stream+1]='F'..(13+math.floor(n/64)) stream[#stream+1]='F'..(13+math.floor(n/8)%8) stream[#stream+1]='F'..(13+n%8) end
stream[#stream+1]='F22'
for i,key in ipairs(stream) do if i~=7 then strict:Key(key) end end
assert(accepted==0)
for i,key in ipairs(stream) do strict:Key(key) if i==7 then strict:Key(key) end end
assert(accepted==0)
for _,key in ipairs(stream) do strict:Key(key) end assert(accepted==1)
strict:Key('F21')
for _=1,31 do now=now+1 strict:Key('F13') end
assert(strict.buffer==nil)

local frames={} local focus,combat,binding,modifier=false,false,'',false
InCombatLockdown=function() return combat end
GetCurrentKeyBoardFocus=function() return focus end
IsModifierKeyDown=function() return modifier end
GetBindingAction=function(_,check) assert(check==true) return binding end
GetTime=function() return now end
UIParent={}
SetBinding=function() error('binding write forbidden') end
SetOverrideBinding=SetBinding
local methods={}
for _,name in ipairs({'SetSize','SetPoint','SetFrameStrata','EnableMouse','Hide'}) do methods[name]=function() end end
methods.SetScript=function(self,n,f) self[n]=f end
methods.EnableKeyboard=function(self,v) self.keyboard=v end
methods.SetPropagateKeyboardInput=function(self,v) assert(v==true) end
methods.CreateTexture=function()
 return {SetSize=function() end,SetPoint=function() end,SetColorTexture=function(_,r,g,b,a) assert(r==g and g==b and a==1) end}
end
CreateFrame=function() local f=setmetatable({},{__index=methods}) frames[#frames+1]=f return f end
binding='USER_BINDING' bad(T.Enable(123)) assert(#frames==0) binding=''
local link=assert(T.Enable(123)) T.frame:OnUpdate() assert(link.ready)
focus=true T.frame:OnUpdate() assert(not link.ready) focus=false
combat=true T.frame:OnUpdate() assert(not link.ready) combat=false
modifier=true T.frame:OnUpdate() assert(not link.ready) modifier=false
T.frame:OnUpdate() assert(link.ready)
local old=T.frame T.Disable() assert(not old.keyboard and not T.frame)
-- Emit cross-language golden frame generated by actual Lua codec.
local s=T.Encode(4294967295,65535,65534,string.char(0,128,255)..'UTF8:\195\169',true)
print((s:gsub('.',function(c) return string.format('%02x',c:byte()) end)))
print('Lua transport: all assertions passed')
