import fs from 'node:fs/promises';import os from 'node:os';import path from 'node:path';import {createHash} from 'node:crypto';import {measure} from './measure.mjs';
const [stage,out,suite="baseline"]=process.argv.slice(2);if(!/^[a-z0-9-]{1,40}$/.test(stage??'')||!out)throw Error('usage: node scripts/auto-router-bench/run.mjs STAGE NEW_OUTPUT_DIRECTORY');
const prompts={code:'Fix this JavaScript function so it includes the last element: function sum(xs) { let n=0; for(let i=0;i<xs.length-1;i++) n+=xs[i]; return n; } Return corrected code and one short explanation.',math:'A box contains 4 red and 6 blue balls. Two are drawn without replacement. Give the exact probability of different colors and a brief derivation.',analysis:'Average service latency fell from 200 ms to 150 ms while traffic shifted toward smaller requests. Explain the confounder and a fair comparison in three concise sentences.'};
const baselineCases=[...Object.keys(prompts).map(family=>({id:`auto-${family}`,model:'auto',family})),...['luna','sol','glm'].map(family=>({id:`explicit-${family}`,model:family==='glm'?'@cf/zai-org/glm-5.3:low':`cloudflare:openai/gpt-6-${family}:low`,family:'analysis'}))];
const familyCases=[{id:'explicit-glm',model:'@cf/zai-org/glm-5.3:low',family:'analysis'},{id:'explicit-kimi',model:'openrouter:moonshotai/kimi-k3:low',family:'analysis'},{id:'explicit-mimo',model:'openrouter:xiaomi/mimo-v2.6-pro:low',family:'analysis'}];
if(!['baseline','families'].includes(suite))throw Error('invalid_suite');const cases=suite==='families'?familyCases:baselineCases;
const keyFile=process.env.AUTO_BENCH_KEY_FILE??path.join(os.homedir(),'.nanocodex/inference-key-batches/teammates-2026-09-21/keys.json');const key=JSON.parse(await fs.readFile(keyFile,'utf8')).keys[Number(process.env.AUTO_BENCH_KEY_INDEX??8)]?.api_key;if(typeof key!=='string'||!key)throw Error('missing_key');
const base=process.env.AUTO_BENCH_BASE_URL??'https://nanocodex.gakonst.workers.dev/v1';const target=new URL(base);if(target.protocol!=='https:'||target.username||target.password||target.search||target.hash)throw Error('invalid_target');
await fs.mkdir(out,{recursive:false});
const cat=await fetch(base+'/models',{headers:{authorization:`Bearer ${key}`},redirect:'manual',signal:AbortSignal.timeout(15000)});const catalog=await cat.json();if(!cat.ok)throw Error(`catalog_http_${cat.status}`);const entries=catalog.data??catalog.models??[];
for(const c of cases)if(c.model!=='auto'&&!entries.some(x=>x.id===c.model))throw Error('case_not_in_live_catalog_'+c.id);
await fs.writeFile(path.join(out,'manifest.json'),JSON.stringify({stage,created_at:new Date().toISOString(),target:base,attempt_cap:cases.length,suite,max_output_tokens:256,no_retries:true,timing_origin:'Mac development caller; cf-ray is ingress, not execution location',cases:cases.map(c=>({...c,prompt_sha256:createHash('sha256').update(prompts[c.family]).digest('hex')})),eligible_ids:entries.map(x=>x.id)},null,2));
for(const c of cases){await fs.appendFile(path.join(out,'reservations.jsonl'),JSON.stringify({case:c.id,at:new Date().toISOString()})+'\n');const result=await measure({url:base+'/responses',key,body:{model:c.model,input:prompts[c.family],stream:true,store:false,max_output_tokens:256}});const row={stage,case:c.id,model_requested:c.model,prompt_family:c.family,...result};const serialized=JSON.stringify(row);if(serialized.includes(key))throw Error('credential_in_result');await fs.appendFile(path.join(out,'results.jsonl'),serialized+'\n');console.log(JSON.stringify({case:c.id,http_status:row.http_status,status:row.status,error:row.error,headers_ms:row.headers_ms,first_delta_ms:row.first_delta_ms,total_ms:row.total_ms,delta_count:row.delta_count,earlier_chunk_deltas:row.deltas_in_earlier_chunk_than_terminal,route:row.route}));if([401,403,429].includes(row.http_status))break;}
