#!/usr/bin/env python3
"""Verify only consumed runtime prompts against pinned Codex revisions.

No upstream source code or model catalog is vendored. --write refreshes the small
set of runtime assets and their provenance from one clean external repository;
verification compares exact bytes.
"""
import argparse
import hashlib
import json
from pathlib import Path
import subprocess

PIN = '36430b36881cf5c289cb48e671cfc9e8b542ae7b'
MODEL_PIN = '49e95cc73f4eb2999b1d14f863c009168df6122b'
SOL_PIN = '5937592c07e7321f6b0469ef34dd58a03c39a84c'
ROOT = Path(__file__).resolve().parents[2]
MANIFEST = ROOT / 'scripts/codex-parity/prompts.json'
# source -> actual consuming asset (no optional prompt inventory)
FILES = {
    'prompts/templates/permissions/sandbox_mode/danger_full_access.md':
        'crates/nanocodex-agent/src/model/prompts/danger_full_access.md',
    'prompts/templates/permissions/approval_policy/never.md':
        'crates/nanocodex-agent/src/model/prompts/never.md',
    'prompts/templates/realtime/backend_prompt.md':
        'crates/nanocodex-voice-protocol/src/backend_prompt.md',
    'prompts/templates/realtime/realtime_start.md':
        'crates/nanocodex-voice-protocol/src/realtime_start.md',
    'prompts/templates/realtime/realtime_end.md':
        'crates/nanocodex-voice-protocol/src/realtime_end.md',
}
GOAL = 'ext/goal/templates/goals/continuation.md'
CATALOG = 'models-manager/models.json'
# Provenance for composition rules, verified externally but never copied locally.
RENDERERS = ['prompts/src/permissions_instructions.rs', 'prompts/src/realtime.rs',
             'core/src/context/realtime_start_instructions.rs',
             'core/src/context/realtime_end_instructions.rs',
             'ext/goal/src/runtime.rs', 'utils/template/src/lib.rs']
MODEL_FIELDS = [
    (PIN, 'gpt-6-astra', 'crates/nanocodex-oai-api/prompts/astra.md'),
    (SOL_PIN, 'gpt-6.1-sol', 'crates/nanocodex-oai-api/prompts/sol.md'),
    (MODEL_PIN, 'gpt-6-luna', 'crates/nanocodex-oai-api/prompts/luna.md'),
]


def digest(content):
    return hashlib.sha256(content).hexdigest()


def revision_bytes(upstream, revision, path):
    return subprocess.check_output(
        ['jj', 'file', 'show', '-r', revision, 'codex-rs/' + path],
        cwd=upstream,
    )


def outputs(upstream, reader=revision_bytes):
    sources = {p: reader(upstream, PIN, p) for p in [*FILES, GOAL, CATALOG, *RENDERERS]}
    generated = {ROOT / target: sources[source] for source, target in FILES.items()}
    fields = []
    catalogs = {PIN: sources[CATALOG]}
    catalogs[MODEL_PIN] = reader(upstream, MODEL_PIN, CATALOG)
    catalogs[SOL_PIN] = reader(upstream, SOL_PIN, CATALOG)
    for revision, slug, target in MODEL_FIELDS:
        models = {m['slug']: m for m in json.loads(catalogs[revision])['models']}
        content = models[slug]['model_messages']['instructions_template'].encode()
        generated[ROOT / target] = content
        fields.append({'model': slug, 'field': 'model_messages.instructions_template',
                       'target': target, 'upstream': revision, 'sha256': digest(content)})
    generated[ROOT / 'js/managed/src/goal-continuation.ts'] = (
        '// Generated by scripts/codex-parity/prompts.py from ' + PIN + '.\n'
        'export const GOAL_CONTINUATION_TEMPLATE = `' + sources[GOAL].decode().replace('\\', '\\\\').replace('`', '\\`').replace('${', '\\${') + '`;\n'
    ).encode()
    manifest = {
        'upstream': PIN,
        'model_upstream': MODEL_PIN,
        'sol_upstream': SOL_PIN,
        'sources': [{'path': p, 'sha256': digest(b), 'bytes': len(b),
                     'role': 'composition reference (external only)' if p in RENDERERS else 'consumed prompt source'}
                    for p, b in sorted(sources.items())],
        'model_sources': [{'path': CATALOG, 'upstream': revision,
                           'sha256': digest(catalogs[revision]),
                           'bytes': len(catalogs[revision]),
                           'role': 'consumed model prompt source'}
                          for revision in [MODEL_PIN, SOL_PIN]],
        'model_fields': fields,
        'outputs': [{'path': str(p.relative_to(ROOT)), 'sha256': digest(b), 'bytes': len(b)}
                    for p, b in sorted(generated.items())],
    }
    generated[MANIFEST] = (json.dumps(manifest, indent=2) + '\n').encode()
    return generated


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument('upstream', type=Path)
    parser.add_argument('--write', action='store_true')
    args = parser.parse_args()
    assert not subprocess.check_output(
        ['jj', 'diff', '--summary'], cwd=args.upstream, text=True
    ).strip(), 'modified upstream'
    for revision in [PIN, MODEL_PIN, SOL_PIN]:
        resolved = subprocess.check_output(
            ['jj', 'log', '-r', revision, '--no-graph', '-T', 'commit_id'],
            cwd=args.upstream,
            text=True,
        ).strip()
        assert resolved == revision, f'missing upstream revision {revision}'
    expected = outputs(args.upstream)
    for path, content in expected.items():
        if args.write:
            path.parent.mkdir(parents=True, exist_ok=True)
            path.write_bytes(content)
        else:
            assert path.read_bytes() == content, f'prompt drift: {path.relative_to(ROOT)}'
    print(f'PASS {len(FILES) + 3} consumed upstream sources; {len(RENDERERS)} external composition references; {len(expected)} outputs; {PIN}; models {MODEL_PIN}; Sol {SOL_PIN}')


if __name__ == '__main__':
    main()
