// Compact Worker-owned projection of docs frontmatter and the public docs route
// set. The focused sync test keeps it aligned with every source page.
export const docsPreview = {
  "/docs": ["Quick start", "Install Nanocodex, authenticate, and run your first coding-agent turn."],
  "/docs/getting-started": ["Installation and authentication", "Install a published Nanocodex artifact and choose an explicit user-facing auth path."],
  "/docs/harness/focused-run": ["Use the eval harness", "Add, run, and inspect one task when you have a complete Nanocodex eval distribution."],
  "/docs/harness/evidence": ["Retained runs and evidence", "Understand generations, attempt history, and the files behind an eval result."],
  "/docs/harness/dashboard-worksets": ["Dashboard and worksets", "Browse retained public worksets or observe a complete local eval ledger."],
  "/docs/harness/read-results": ["Read a harness result", "Separate verifier outcomes, infrastructure health, harness behavior, and cost."],
  "/docs/evals": ["Evals", "Understand the retained VM eval boundary and inspect published Nanocodex evidence."],
  "/docs/sdks/rust": ["Rust SDK", "Build one retained coding-agent session with the canonical Nanocodex facade."],
  "/docs/sdks/rust/agent-lifecycle": ["Rust agent lifecycle", "Build one owned session, send follow-on prompts, and stop every resource cleanly."],
  "/docs/sdks/rust/turns-events-control": ["Rust turns, events, and control", "Accept work quickly, await typed results independently, and steer or cancel one turn."],
  "/docs/sdks/rust/tools-code-mode-mcp": ["Rust tools, Code Mode, and MCP", "Add typed application capabilities without moving the agent loop out of Rust."],
  "/docs/sdks/rust/handles-forks-subagents": ["Rust handles, forks, and subagents", "Share commands cheaply, fork committed context, or give tools a weak child-agent capability."],
  "/docs/sdks/rust/durability": ["Rust durability", "Journal accepted operations and recover them without introducing a framework-owned agent loop."],
  "/docs/core/owned-agent": ["The owned agent", "Embed the Rust-owned Codex lifecycle behind one cheap command handle."],
  "/docs/core/tools-code-mode": ["Tools and Code Mode", "Make Code Mode the default, then add typed Rust, hosted, or deferred MCP tools."],
  "/docs/core/branching": ["Branches and subagents", "Clone cheap handles, fork retained context, or delegate through an optional task tree."],
  "/docs/core/durability": ["Durable execution", "Resume accepted work with Rust-owned journaling over a tiny host store contract."],
  "/docs/sdks/javascript": ["TypeScript and JavaScript SDK", "Run the Rust-owned headless agent lifecycle from Node, browser Workers, or React-owned Workers."],
  "/docs/sdks/javascript/install-entrypoints": ["Install TypeScript and JavaScript", "Choose the published Node, package Worker, or Web API host entrypoint and keep generated WASM internals private."],
  "/docs/sdks/javascript/agent-lifecycle": ["TypeScript agent lifecycle", "Submit retained turns, watch events independently, and release every JavaScript and Rust owner."],
  "/docs/sdks/javascript/tools-code-mode-subagents": ["TypeScript tools, Code Mode, and subagents", "Register host tools, compose them in Code Mode, and select the linked Rust task-tree extension."],
  "/docs/sdks/javascript/transports-auth": ["TypeScript transports and authentication", "Choose who owns credentials and WebSocket creation for one OpenAI Responses lifecycle."],
  "/docs/sdks/javascript/browser-workspace": ["Browser Worker and workspace", "Run the Rust agent in a Worker with persistent OPFS, browser tools, and application-owned UI."],
  "/docs/sdks/javascript/react": ["React integration", "Let React own a module Worker and external store without making presentation part of the agent SDK."],
  "/docs/capabilities/web-agent": ["Web agent", "Run the Codex lifecycle and common coding tools locally in a browser Worker."],
  "/docs/deployments": ["Deployment patterns", "Run one owned agent in a CLI, browser, server isolate, durable actor, or cloud sandbox."],
  "/docs/deployments/cloudflare": ["Cloudflare Durable Objects", "Run Rust/WASM inside one SQLite-backed Durable Object with an R2-backed Sandbox workspace."],
  "/docs/deployments/vercel": ["Vercel Workflows", "Reconstruct Rust/WASM in Function steps from an application-owned PostgreSQL journal."],
  "/docs/sdks/python": ["Python SDK", "A thin PyO3 binding over the native owned Rust lifecycle."],
  "/docs/capabilities/vm-sandboxes": ["VMs and sandboxes", "Keep fast local tools, then escape to a retained VM or hosted sandbox when needed."],
  "/docs/capabilities/voice": ["Voice", "Realtime audio delegates coding work into one retained agent session."],
  "/docs/examples/tact": ["Built with Nanocodex: Tact", "Nanocodex owns the agent lifecycle; Tact owns application policy."],
  "/docs/stability": ["Stability and scope", "Adopt the supported OpenAI lifecycle without assuming provider portability."],
} as const satisfies Record<string, readonly [title: string, description: string]>;
