'use strict';
const $ = id => document.getElementById(id);
const fields = ['version', 'class', 'spec', 'zone', 'goal'];
const state = {connected:false, project:null, thread:null, agentThread:null, gameThread:null, mode:'agent', context:{}, busy:false, load:0, recognition:null, recording:false, pendingSend:null, voiceStatus:null, recorder:null, stream:null, voiceTimer:null, voiceStarting:false, transcribing:false, leaving:false, settingsPlan:null};
const help = {agent:'Delegate a task to your Nanocodex agent.', lore:'Explore the story. Mention your spoiler preferences.', hint:'Ask for a nudge and keep the discovery yours.', build:'Plan talents and gear for your version and specialization.', pvp:'Discuss matchups, positioning, and competitive play.', pve:'Plan encounters, rotations, and group content.',settings:'Plan keybinds and HUD changes locally. Nothing is applied automatically.'};
const welcome = $('messages').innerHTML;
function notice(message='',kind='info') {
 const box=$('notice');box.textContent=message;box.hidden=!message;box.dataset.kind=kind;
 box.setAttribute('role',kind==='error'?'alert':'status');
 if(message&&window.wowNotify)window.wowNotify({message,kind});
}
async function api(path, body) {
  const response = await fetch(path, {method:body?'POST':'GET', headers:body?{'Content-Type':'application/json'}:{}, body:body?JSON.stringify(body):undefined});
  let data; try {data=await response.json();} catch {throw new Error(`The companion server returned an unreadable response (${response.status}). Check that the service is running.`);}
  if (!response.ok) throw new Error(typeof data.error==='string'?data.error:(data.error?.message || data.message || `Request failed (${response.status}). Check the connection settings.`));
  return data;
}
function selectMode(mode){
 if(state.busy)return;
 const family=m=>m==='agent'?'agent':m==='settings'?'settings':'game';const previous=family(state.mode),next=family(mode);
 if(previous!==next){if(previous==='agent')state.agentThread=state.thread;else if(previous==='game')state.gameThread=state.thread;state.thread=next==='agent'?state.agentThread:next==='game'?state.gameThread:null;state.load++;stopPolling();delete $('messages').dataset.thread;}
 state.mode=mode;
 if(next==='settings'){renderSettings(state.settingsPlan);notice('Local settings planner works without account login. Paste the generated commands in WoW chat to execute them.');}
 else if(previous!==next){$('messages').innerHTML=welcome;if(state.thread){loadMessages(state.thread).catch(e=>notice(e.message,'error'));startPolling();}notice();}
 $('newThread').textContent=next==='agent'?'↩ Project root':next==='settings'?'＋ Clear settings plan':'＋ New game conversation';
 $('threadTitle').textContent=next==='agent'?(state.thread?'Agent conversation':'Project root conversation'):next==='settings'?'WoW settings · local planner':'Game companion · separate conversation';
 document.querySelectorAll('.mode-tabs button').forEach(b=>{b.classList.toggle('active',b.dataset.mode===mode);b.setAttribute('aria-pressed',String(b.dataset.mode===mode));});
 $('modeHelp').textContent=help[mode]+(next==='game'?' Uses a separate game conversation.':'');$('prompt').placeholder=next==='settings'?'Try “bind map to shift m” or “UI scale 85%”':'What are we working on?';updateSend();
}
function updateSend() {$('send').disabled=state.busy||(!state.connected&&state.mode!=='settings'); $('send').textContent=state.busy?'Working…':state.mode==='settings'?'Create plan ↑':'Send ↑';$('newThread').disabled=state.busy;$('projects').disabled=state.busy;}
function appendMessage(role,text) {const el=document.createElement('article');el.className='message '+(role==='user'?'user':'assistant');const label=document.createElement('div');label.className='message-label';label.textContent=role==='user'?'YOU':role==='assistant'?'NANOCODEX':String(role).toUpperCase();const body=document.createElement('div');body.className='message-body';body.textContent=String(text??'');el.append(label,body);if(role==='assistant'){const copy=document.createElement('button');copy.type='button';copy.textContent='Copy reply for WoW';copy.onclick=async()=>{try{await navigator.clipboard.writeText('nc1:'+encodeURIComponent(String(text??'')));notice('Reply copied. In WoW, open /nc reply, paste into the box, and click Show answer.','success');}catch{notice('Clipboard unavailable. Select and copy the response text, then paste into /nc reply.','error');}};el.append(copy);}$('messages').append(el);$('messages').scrollTop=$('messages').scrollHeight;}
const messageCache=new Map();
let pollTimer=null,pollCount=0,pollInFlight=false;
const messageRequests=new Map();
async function loadMessages(thread, speak=false){
 if(messageRequests.has(thread))return messageRequests.get(thread);
 const serial=++state.load;
 const request=(async()=>{const data=await api('/api/messages?thread_id='+encodeURIComponent(thread));if(serial!==state.load||state.thread!==thread)return;
 const messages=Array.isArray(data.messages)?data.messages:[];const signature=JSON.stringify(messages);const previous=messageCache.get(thread);const assistants=messages.filter(m=>m.role==='assistant'&&m.text);const assistantSignature=JSON.stringify(assistants.map(m=>m.text));
 messageCache.set(thread,{signature,assistantSignature});
 if(!previous||previous.signature!==signature||$('messages').dataset.thread!==thread){$('messages').replaceChildren();$('messages').dataset.thread=thread;if(!messages.length){const p=document.createElement('p');p.className='muted';p.textContent='Waiting for conversation messages…';$('messages').append(p);}if(data.has_more){const note=document.createElement('p');note.className='muted';note.textContent='Showing the messages returned by the server. More conversation history is available in Nanocodex.';$('messages').append(note);}messages.forEach(m=>appendMessage(m.role,m.text));}
 if(speak&&previous&&assistantSignature!==previous.assistantSignature&&assistants.length){readResponse(assistants[assistants.length-1].text);window.wowNotify?.({kind:'reply',title:'New reply',message:state.mode==='agent'?'Your agent has replied.':'Your game companion has replied.'});}
 })();messageRequests.set(thread,request);try{return await request;}finally{messageRequests.delete(thread);}
}
function stopPolling(){clearTimeout(pollTimer);pollTimer=null;}
function startPolling(){stopPolling();pollCount=0;if(!state.thread)return;pollTimer=setTimeout(pollConversation,document.hidden?5000:2000);}
async function pollConversation(){pollTimer=null;if(!state.thread||state.leaving)return;if(pollCount>=300){notice('Live updates paused after the polling window. Refresh the workspace or reselect this conversation to continue.');return;}
 if(!state.busy&&!pollInFlight){pollInFlight=true;pollCount++;try{await loadMessages(state.thread,true);}catch(e){notice('Conversation refresh failed: '+e.message+' Use Refresh to try again.','error');}finally{pollInFlight=false;}}
 if(state.thread&&!state.leaving)pollTimer=setTimeout(pollConversation,document.hidden?5000:2000);
}
document.addEventListener('visibilitychange',()=>{if(!document.hidden&&state.thread&&!pollTimer)startPolling();});
async function loadThreads() {const project=state.project; if(!project){$('threads').replaceChildren();return;}const data=await api('/api/threads?project_id='+encodeURIComponent(project));if(project!==state.project)return;$('threads').replaceChildren();const threads=Array.isArray(data.threads)?data.threads:[];if(!threads.length){const p=document.createElement('p');p.className='empty-list muted';p.textContent='No conversations yet. Start one below.';$('threads').append(p);}threads.forEach(t=>{const b=document.createElement('button');b.className='thread';b.classList.toggle('active',t.id===state.thread);b.textContent=t.title||'Untitled conversation';if(t.status){const s=document.createElement('small');s.textContent=t.status;b.append(s);}b.addEventListener('click',async()=>{if(state.busy)return;selectMode('agent');state.thread=t.id;state.agentThread=t.id;$('threadTitle').textContent=t.title||'Conversation';document.querySelectorAll('.thread').forEach(el=>el.classList.toggle('active',el===b));$('sidebar').classList.remove('show');notice();try{await loadMessages(t.id);startPolling();}catch(e){notice(e.message,'error');}});$('threads').append(b);});}
function newThread(){if(state.busy)return;if(state.mode==='settings'){state.settingsPlan=null;renderSettings(null);$('prompt').focus();return;}state.load++;stopPolling();state.thread=null;delete $('messages').dataset.thread;if(state.mode==='agent')state.agentThread=null;else state.gameThread=null;$('threadTitle').textContent=state.mode==='agent'?'Project root conversation':'New game conversation';$('messages').innerHTML=welcome;document.querySelectorAll('.thread').forEach(b=>b.classList.remove('active'));$('prompt').focus();notice(state.mode==='agent'?'Your next message continues the selected project root conversation.':'');}
async function refresh(){try {const status=await api('/api/status');state.connected=Boolean(status.connected);state.voiceStatus=status.voice||{available:false};updateVoiceCapability(); const cliAuth=true; $('connectionLabel').textContent=state.connected?'Workspace connected':'Workspace disconnected';$('statusDot').classList.toggle('connected',state.connected);updateSend();if(!state.connected){notice((status.error?status.error+' ':'')+(cliAuth?'Open Connection settings for CLI login instructions.':'Connect your Nanocodex workspace in Connection settings to send messages.'));$('threads').textContent='Connect to see your conversations.';return;}const data=await api('/api/projects');const projects=Array.isArray(data.projects)?data.projects:[];const prior=state.project;$('projects').replaceChildren();const placeholder=document.createElement('option');placeholder.value='';placeholder.textContent=projects.length?'Select a project':'No projects available';$('projects').append(placeholder);projects.forEach(p=>{const o=document.createElement('option');o.value=p.id;o.textContent=p.name||'Untitled project';$('projects').append(o);});state.project=projects.some(p=>p.id===prior)?prior:(projects[0]?.id||null);$('projects').value=state.project||'';if(state.project!==prior&&state.mode==='agent')newThread();await loadThreads();if(state.thread)startPolling();notice(projects.length?'':'No projects are available. Create a project in Nanocodex, then refresh.');}catch(e){state.connected=false;$('connectionLabel').textContent='Connection unavailable';$('statusDot').classList.remove('connected');updateSend();notice(e.message,'error');}}
$('projects').addEventListener('change',async()=>{selectMode('agent');state.project=$('projects').value||null;newThread();try{await loadThreads();}catch(e){notice(e.message,'error');}});
$('newThread').onclick=newThread;$('refresh').onclick=refresh;
document.querySelectorAll('.mode-tabs button').forEach(b=>b.onclick=()=>selectMode(b.dataset.mode));
$('messages').addEventListener('click',e=>{const b=e.target.closest('[data-prompt]');if(!b)return;selectMode(b.dataset.mode);$('prompt').value=b.dataset.prompt;$('prompt').focus();});
$('compose').addEventListener('submit',async e=>{e.preventDefault();const text=$('prompt').value.trim();if(!text||state.busy)return;if(state.mode==='settings'){await planSettings(text);return;}if(!state.connected){notice('Connect your workspace before sending.');return;}if(state.mode==='agent'&&!state.project){notice('Select a project first. If none are listed, create one in Nanocodex and refresh.');return;}state.busy=true;updateSend();notice();if($('welcome'))$('messages').replaceChildren();appendMessage('user',text);const context={...state.context};fields.forEach(f=>{context[f]=$(f).value.trim();});try {const payload={thread_id:state.thread||null,project_id:state.mode==='agent'?state.project:null,text,mode:state.mode,context,model:'luna'};const signature=JSON.stringify(payload);if(state.pendingSend?.signature!==signature)state.pendingSend={signature,key:crypto.randomUUID()};const data=await api('/api/send',{...payload,idempotency_key:state.pendingSend.key});state.pendingSend=null;$('prompt').value='';state.thread=data.thread_id||state.thread;if(state.mode==='agent')state.agentThread=state.thread;else state.gameThread=state.thread;if(state.thread){$('threadTitle').textContent=state.mode==='agent'?'Agent conversation':'Game companion · separate conversation';if(!messageCache.has(state.thread))messageCache.set(state.thread,{signature:'',assistantSignature:'[]'});await loadMessages(state.thread,true);startPolling();await loadThreads();}else {notice('The server accepted the request but returned no conversation ID. Refresh your conversations before sending again.');}}catch(e){notice(e.message+' Your draft is kept below. If the request may have reached the server, refresh the conversation before retrying.','error');}finally{state.busy=false;updateSend();}});
$('prompt').addEventListener('keydown',e=>{if(e.key==='Enter'&&!e.shiftKey&&!e.isComposing){e.preventDefault();$('compose').requestSubmit();}});
$('import').onclick=()=>{try{const raw=JSON.parse($('importContext').value);if(!raw||typeof raw!=='object'||Array.isArray(raw))throw new Error('Expected a JSON object.');const c=raw.context&&typeof raw.context==='object'&&!Array.isArray(raw.context)?raw.context:raw;state.context=c;if(raw.type==='nanocodex.ask'&&typeof raw.prompt==='string'){selectMode('hint');$('prompt').value=raw.prompt;$('prompt').focus();}fields.forEach(f=>{const nested={version:c.client?.version,class:c.character?.class,spec:c.specialization?.name,zone:c.location?.zone};const value=c[f]??nested[f]??c.character?.[f];if(value!==undefined)$(f).value=typeof value==='string'||typeof value==='number'?String(value):JSON.stringify(value);});window.wowNotify?.({kind:'success',message:'Character context updated.'});$('importStatus').textContent='Snapshot imported'+(typeof c.capturedAt==='number'?' · '+new Date(c.capturedAt*1000).toLocaleString():'')+'. Review the fields above. This is a manual snapshot, not live game data.';}catch(e){$('importStatus').textContent='Could not import: '+e.message;}};
$('settings').onclick=()=>$('connectionDialog').showModal();$('shortcuts').onclick=()=>$('helpDialog').showModal();document.querySelectorAll('.close-dialog').forEach(b=>b.onclick=()=>b.closest('dialog').close());$('menu').onclick=()=>$('sidebar').classList.toggle('show');$('contextToggle').onclick=()=>{if(matchMedia('(max-width:900px)').matches){$('contextPanel').classList.toggle('show');$('contextToggle').setAttribute('aria-expanded',String($('contextPanel').classList.contains('show')));}else{$('contextPanel').hidden=!$('contextPanel').hidden;$('contextToggle').setAttribute('aria-expanded',String(!$('contextPanel').hidden));}};
function readResponse(text){if(!$('readAloud').checked)return;if(!('speechSynthesis'in window)){notice('Read aloud is unavailable in this browser. You can read the response in the conversation.');return;}speechSynthesis.cancel();if(!speechSynthesis.getVoices().length){notice('No browser speech voices are installed or ready. Check your system speech setup, or read the response below.');return;}const utterance=new SpeechSynthesisUtterance(text);utterance.onend=()=>$('stopSpeech').hidden=true;utterance.onerror=()=>{$('stopSpeech').hidden=true;notice('Audio could not be played. Check browser audio permissions or continue reading the response.');};$('stopSpeech').hidden=false;speechSynthesis.speak(utterance);}
function stopSpeech(){if('speechSynthesis'in window)speechSynthesis.cancel();$('stopSpeech').hidden=true;}$('stopSpeech').onclick=stopSpeech;$('readAloud').onchange=()=>{if(!$('readAloud').checked)stopSpeech();};
function toggleBrowserVoice(){const Recognition=window.SpeechRecognition||window.webkitSpeechRecognition;if(!Recognition){notice('Voice input is not supported by this browser. Linux browser support varies. Type your message below or use your desktop dictation tool.');$('prompt').focus();return;}if(state.recording){state.recognition.stop();return;}try{const r=new Recognition();state.recognition=r;r.lang=navigator.language||'en-US';r.continuous=false;r.interimResults=false;r.onstart=()=>{state.recording=true;$('voice').classList.add('recording');$('voice').setAttribute('aria-label','Stop voice input');notice('Browser speech service listening… Speak your message. Review the transcript before sending.');};r.onresult=e=>{const text=Array.from(e.results).map(result=>result[0].transcript).join(' ');$('prompt').value=[$('prompt').value.trim(),text].filter(Boolean).join(' ');$('prompt').focus();notice('Voice transcribed. Review your message, then send.','success');};r.onerror=e=>{const messages={'not-allowed':'Microphone permission was denied. Allow microphone access in your browser settings or type your message.','audio-capture':'No working microphone was found. Check your input device or type your message.','network':'The browser speech service is unavailable. Check your network or type your message.','no-speech':'No speech was detected. Try again or type your message.','service-not-allowed':'Your browser speech service is disabled. Use typing or desktop dictation.'};notice(messages[e.error]||'Voice input stopped ('+e.error+'). You can type your message instead.','error');};r.onend=()=>{state.recording=false;$('voice').classList.remove('recording');$('voice').setAttribute('aria-label','Start voice input');if($('notice').textContent.startsWith('Listening'))notice('Voice input stopped. You can try again or type your message.');};r.start();}catch(e){notice('Voice input could not start. '+e.message+' You can type your message instead.');}}
$('voice').onclick=toggleVoice;document.addEventListener('keydown',e=>{if(!e.altKey||!e.shiftKey||e.ctrlKey||e.metaKey||document.querySelector('dialog[open]'))return;const key=e.key.toLowerCase();if(!['n','v','p','s'].includes(key))return;e.preventDefault();if(key==='n'){$('prompt').focus();$('prompt').scrollIntoView({block:'nearest'});}if(key==='s'){selectMode('settings');$('prompt').focus();}if(key==='v')toggleVoice();if(key==='p'){$('sidebar').classList.add('show');$('projects').focus();}});
window.addEventListener('pagehide',()=>{state.leaving=true;stopPolling();stopSpeech();if(state.recorder?.state==='recording')state.recorder.stop();releaseMicrophone();if(state.recording)state.recognition?.abort();});
if(!('speechSynthesis'in window)){$('readAloud').disabled=true;$('readAloud').parentElement.title='Speech playback is unavailable in this browser';}
refresh();

$('checkConnection').onclick=async()=>{await refresh();if(state.connected)$('connectionDialog').close();};
const browserRecognition=Boolean(window.SpeechRecognition||window.webkitSpeechRecognition);
$('voiceCapability').textContent=browserRecognition?'Browser dictation is experimental on Linux; it needs microphone access and a working browser speech service.':'Browser dictation is unavailable here. Type, or use your desktop dictation tool to insert text.';
function launchAction(){const action=location.hash.toLowerCase();if(!['#voice','#projects'].includes(action))return;history.replaceState(null,'',location.pathname+location.search);if(action==='#projects'){$('sidebar').classList.add('show');$('projects').focus();}else{$('prompt').focus();toggleVoice();}}
window.addEventListener('hashchange',launchAction);
launchAction();

function updateVoiceCapability(){
 const local=state.voiceStatus?.available===true;
 $('voiceCapability').textContent=local?'Local Whisper dictation · microphone recording stops after 60 seconds. Review the transcript before sending.':(browserRecognition?'Local dictation unavailable. Browser speech is a separate, experimental Linux fallback.':'Dictation unavailable. Configure local Whisper on the server, or type your message.');
 $('voice').setAttribute('data-wow-tooltip',local?'Record with local Whisper (Alt+Shift+V)':'Browser speech fallback (Alt+Shift+V)');
}
function releaseMicrophone(){clearTimeout(state.voiceTimer);state.voiceTimer=null;state.stream?.getTracks().forEach(track=>track.stop());state.stream=null;state.recording=false;$('voice').classList.remove('recording');$('voice').setAttribute('aria-label','Start voice input');}
async function toggleVoice(){
 if(state.voiceStarting||state.transcribing){notice(state.transcribing?'Transcribing locally… Your draft will appear when ready.':'Waiting for microphone permission…');return;}
 if(state.recorder?.state==='recording'){state.recorder.stop();releaseMicrophone();return;}
 if(state.recording){state.recognition?.stop();return;}
 if(!state.voiceStatus){try{const status=await api('/api/status');state.voiceStatus=status.voice||{available:false};updateVoiceCapability();}catch(e){notice('Could not check local voice availability. '+e.message);return;}}
 if(!state.voiceStatus.available){toggleBrowserVoice();return;}
 if(!navigator.mediaDevices?.getUserMedia||!window.MediaRecorder){notice('Microphone recording is unavailable in this browser. Open the companion on localhost or HTTPS in a browser supporting MediaRecorder, or type your message.');return;}
 state.voiceStarting=true;
 try{
  const stream=await navigator.mediaDevices.getUserMedia({audio:true});state.stream=stream;
  if(state.leaving){releaseMicrophone();return;}
  const mime=['audio/webm;codecs=opus','audio/ogg;codecs=opus','audio/webm','audio/ogg','audio/mp4'].find(type=>MediaRecorder.isTypeSupported(type));
  const recorder=new MediaRecorder(stream,mime?{mimeType:mime}:undefined);state.recorder=recorder;const chunks=[];let failed=false;
  recorder.ondataavailable=e=>{if(e.data.size)chunks.push(e.data);};
  recorder.onerror=()=>{failed=true;releaseMicrophone();notice('Microphone recording failed. Check your input device and try again, or type your message.','error');};
  recorder.onstop=async()=>{
   releaseMicrophone();state.recorder=null;if(failed||state.leaving)return;
   const audio=new Blob(chunks,{type:recorder.mimeType||mime||'audio/webm'});
   if(!audio.size){notice('No audio was recorded. Check your microphone and try again.');return;}
   if(audio.size>8*1024*1024){notice('Recording is too large. Try a shorter message.');return;}
   state.transcribing=true;$('voice').disabled=true;notice('Transcribing with local Whisper…','progress');
   try{const response=await fetch('/api/transcribe',{method:'POST',headers:{'Content-Type':audio.type},body:audio});let result;try{result=await response.json();}catch{throw new Error('The transcription server returned an unreadable response.');}if(!response.ok)throw new Error(typeof result.error==='string'?result.error:'Local transcription failed.');if(typeof result.text!=='string'||!result.text.trim())throw new Error('No speech was recognized. Check your microphone and try again.');$('prompt').value=[$('prompt').value.trim(),result.text.trim()].filter(Boolean).join(' ');$('prompt').focus();notice('Local transcript ready. Review your message, then send.','success');}catch(e){notice(e.message+' You can type your message instead.','error');}finally{state.transcribing=false;$('voice').disabled=false;}
  };
  recorder.start();state.recording=true;$('voice').classList.add('recording');$('voice').setAttribute('aria-label','Stop recording and transcribe');notice('Recording locally… Press the voice button again to transcribe. Maximum 60 seconds.','progress');state.voiceTimer=setTimeout(()=>{if(recorder.state==='recording')recorder.stop();releaseMicrophone();},60000);
 }catch(e){releaseMicrophone();notice(e.name==='NotAllowedError'?'Microphone access was denied. Allow microphone permission in your browser, or type your message.':'Could not start microphone recording: '+e.message+'. You can type your message instead.');}
 finally{state.voiceStarting=false;}
}

function isSettingsCommand(command){return typeof command==='string'&&/^\/nc settings (?:undo|(?:preview|apply) (?:bind [A-Z0-9-]+ (?:TOGGLEWORLDMAP|TOGGLECHARACTER0|TOGGLEBAG[1-4]|OPENALLBAGS|ACTIONBUTTON(?:[1-9]|1[0-2])|MULTIACTIONBAR[1-7]BUTTON(?:[1-9]|1[0-2]))|unbind [A-Z0-9-]+|hud scale (?:0\.\d+|1(?:\.0+)?)|hud nameplates (?:on|off)))$/.test(command);}
function renderSettings(plan){
 const area=$('messages');area.replaceChildren();const panel=document.createElement('section');panel.className='settings-plan';
 const title=document.createElement('h2');title.textContent=plan?'Review your settings plan':'Make the game feel like yours';panel.append(title);
 const intro=document.createElement('p');intro.className='muted';intro.textContent='Describe one keybind or HUD change. This local planner creates addon commands; it does not control WoW.';panel.append(intro);
 if(!plan){const examples=document.createElement('div');examples.className='settings-examples';['Bind map to shift m','Unbind shift m','UI scale 85%','Enemy nameplates on','Undo'].forEach(text=>{const b=document.createElement('button');b.type='button';b.className='secondary';b.textContent=text;b.onclick=()=>{$('prompt').value=text;$('prompt').focus();};examples.append(b);});panel.append(examples);}
 else{const summary=document.createElement('p');summary.textContent=plan.summary||'Review the commands below.';panel.append(summary);
 for(const [key,label] of [['preview_command','Copy preview'],['apply_command','Copy apply'],['undo_command','Copy undo']]){const command=plan[key];if(!command)continue;if(!isSettingsCommand(command)){const error=document.createElement('p');error.textContent='The server returned an unsupported command. It was not made available to copy.';panel.append(error);continue;}const row=document.createElement('div');row.className='command-row';const input=document.createElement('input');input.readOnly=true;input.value=command;input.setAttribute('aria-label',label.replace('Copy','')+' command');const button=document.createElement('button');button.type='button';button.className='secondary';button.textContent=label;button.onclick=async()=>{try{if(!navigator.clipboard?.writeText)throw new Error('Clipboard unavailable');await navigator.clipboard.writeText(command);notice('Command copied. Paste it in WoW chat. Nothing has been applied by this companion.');}catch{input.focus();input.select();notice('Command selected. Press Ctrl+C, then paste it in WoW chat.');}};row.append(input,button);panel.append(row);}
 const warnings=Array.isArray(plan.warnings)?plan.warnings:plan.warnings?[plan.warnings]:[];warnings.forEach(text=>{const p=document.createElement('p');p.className='settings-warning';p.textContent=String(text);panel.append(p);});}
 const instructions=document.createElement('p');instructions.className='settings-instructions';instructions.textContent='Paste preview in WoW chat to inspect the change, then paste apply when ready. Protected changes queue in combat and run afterward. Undo is also a command you execute in WoW. The addon must be installed; this page cannot confirm execution.';panel.append(instructions);area.append(panel);
}
async function planSettings(text){state.busy=true;updateSend();notice();try{const plan=await api('/api/settings/plan',{text});state.settingsPlan=plan;renderSettings(plan);$('prompt').value='';notice('Plan ready to review. No game settings have been changed.');}catch(e){notice(e.message+' Your settings request is kept below.');}finally{state.busy=false;updateSend();}}

// Explicit paste transport: import a question captured in WoW; never auto-send it.
$('prompt').addEventListener('paste',event=>{try{const raw=JSON.parse(event.clipboardData.getData('text/plain'));if(raw.type!=='nanocodex.ask'||typeof raw.prompt!=='string')return;event.preventDefault();$('importContext').value=JSON.stringify(raw);$('import').click();notice('WoW question imported. Choose a mode and press Send.');}catch{}});


async function refreshBridgeStatus(){
 const label=$('bridgeStatus'); if(!label)return;
 try{
  const bridge=await api('/api/bridge');
  if(!bridge.available)label.textContent=bridge.message||'Waiting for WoW connection service.';
  else if(bridge.error)label.textContent='WoW: '+bridge.error;
  else if(!bridge.fresh)label.textContent='WoW connection status is stale. The service may have stopped.';
  else label.textContent='WoW: '+(bridge.message||bridge.state||bridge.lifecycle||'waiting for addon');
 }catch{label.textContent='WoW connection status unavailable.';}
}
refreshBridgeStatus();
setInterval(()=>{if(!document.hidden)refreshBridgeStatus();},3000);
