'use strict';
// Account operations are explicit. Imported addon requests only populate this review UI.
const management = {projects:[], threads:[], closed:false, busy:false, draftKey:null, details:null, history:[], cursor:null, uncertain:false};
const makeControl=(id,label,parent)=>{const b=document.createElement('button');b.id=id;b.type='button';b.className='secondary';b.textContent=label;parent.append(b);return b;};
const projectTools=document.createElement('div');projectTools.className='management-tools';$('projects').after(projectTools);
makeControl('createProject','New project',projectTools);makeControl('renameProject','Rename project',projectTools);
const chatTools=document.createElement('div');chatTools.className='management-tools';$('newThread').after(chatTools);
makeControl('createChat','New chat',chatTools);makeControl('renameChat','Rename chat',chatTools);makeControl('closeChat','Close chat',chatTools);
const search=document.createElement('input');search.id='chatSearch';search.placeholder='Search chats';search.setAttribute('aria-label','Search chats');chatTools.after(search);
const filters=document.createElement('div');filters.className='management-tools';search.after(filters);makeControl('showClosed','Show closed',filters);makeControl('copyWorkspace','Copy workspace for WoW',filters);
const activity=document.createElement('div');activity.id='chatActivity';activity.className='management-tools';$('messages').before(activity);
const activityLabel=document.createElement('span');activityLabel.id='activityLabel';activityLabel.textContent='Select a chat to see its status.';activity.append(activityLabel);
makeControl('loadEarlier','Load earlier messages',activity);$('loadEarlier').hidden=true;
makeControl('cancelTurn','Stop active turn',activity);$('cancelTurn').hidden=true;
makeControl('steerTurn','Steer active turn',activity);$('steerTurn').hidden=true;
const dialog=document.createElement('dialog');dialog.id='manageDialog';
dialog.innerHTML='<form id="manageForm"><div class="dialog-head"><h2 id="manageTitle"></h2><button type="button" id="manageClose" aria-label="Close management dialog">×</button></div><p id="manageExplanation"></p><label id="manageNameLabel">Name<input id="manageName" maxlength="160" autocomplete="off"></label><label id="manageInputLabel">First message<textarea id="manageInput" rows="4" maxlength="24000"></textarea></label><p id="manageError" role="alert"></p><button type="submit" id="manageConfirm" class="send">Confirm</button></form>';
document.body.append(dialog);let pendingManagement=null;
$('manageClose').onclick=()=>{if(!management.busy)dialog.close();};dialog.addEventListener('cancel',e=>{if(management.busy)e.preventDefault();});
function safeDraftKey(){return state.mode==='agent'?'agent:'+(state.thread||state.project||'new'):'game:'+(state.thread||state.mode);}
function saveDraft(){if(management.draftKey)try{sessionStorage.setItem('wow.draft.'+management.draftKey,$('prompt').value);}catch{}}
function restoreDraft(){const key=safeDraftKey();if(key===management.draftKey)return;management.draftKey=key;try{$('prompt').value=sessionStorage.getItem('wow.draft.'+key)||'';}catch{$('prompt').value='';}}
$('prompt').addEventListener('input',saveDraft);
const coreSelectMode=selectMode;selectMode=function(mode){saveDraft();coreSelectMode(mode);restoreDraft();};
const coreNewThread=newThread;newThread=function(){saveDraft();coreNewThread();restoreDraft();updateManagement();};$('newThread').onclick=newThread;
const coreApi=api;api=async function(path,body){if(!body&&path.startsWith('/api/threads?')&&!path.includes('closed='))path+='&closed='+String(management.closed);const result=await coreApi(path,body);if(body&&path==='/api/send'){try{sessionStorage.removeItem('wow.draft.'+management.draftKey);}catch{}}if(!body&&path.startsWith('/api/messages?'))rememberHistory(path,result);if(!body&&path==='/api/projects'){management.projects=result.projects||[];updateManagement();}if(!body&&path.startsWith('/api/threads?')){management.threads=result.threads||[];setTimeout(updateManagement,0);}return result;};
const coreLoadMessages=loadMessages;loadMessages=async function(thread,speak=false){restoreDraft();await coreLoadMessages(thread,speak);renderHistory(thread);await refreshActivity(thread);updateManagement();};
const coreLoadThreads=loadThreads;loadThreads=async function(){await coreLoadThreads();filterThreads();updateManagement();};
function filterThreads(){const term=search.value.trim().toLocaleLowerCase();$('threads').querySelectorAll('.thread').forEach(b=>{b.hidden=!!term&&!b.textContent.toLocaleLowerCase().includes(term);});}
search.oninput=filterThreads;
function updateManagement(){const ready=state.connected&&!state.busy&&!management.busy;for(const id of ['createProject','createChat','renameProject','renameChat','closeChat','copyWorkspace'])$(id).disabled=!ready||(['createChat','renameProject','copyWorkspace'].includes(id)&&!state.project)||(['renameChat','closeChat'].includes(id)&&!state.thread);$('closeChat').disabled=!ready||!management.threads.some(t=>t.id===state.thread);$('closeChat').textContent=management.closed?'Restore chat':'Close chat';}
function review(action,seed={}){
 if(management.busy)return;
 const labels={create_project:'Create project',rename_project:'Rename project',create_chat:'Create chat',rename_chat:'Rename chat',close_chat:'Close chat',restore_chat:'Restore chat',cancel_turn:'Stop active turn',steer_turn:'Steer active turn'};
 if(!labels[action])throw Error('Unsupported action.');
 const project=seed.project_id||state.project,thread=seed.thread_id||state.thread;
 if(action!=='create_project'&&!project)throw Error('Select a project first.');
 if(['rename_chat','close_chat','restore_chat','cancel_turn','steer_turn'].includes(action)&&!thread)throw Error('Select a chat first.');
 pendingManagement={action,project_id:project,thread_id:thread,turn_id:seed.turn_id||management.details?.active_turns?.[0],idempotency_key:crypto.randomUUID()};management.uncertain=false;
 $('manageTitle').textContent=labels[action];$('manageExplanation').textContent=action.includes('rename')?'This name is saved in the companion on this computer. It does not rename the conversation on other devices.':action==='close_chat'?'Close this chat in the companion. This does not stop its agent or delete its history.':action==='cancel_turn'?'Stop the selected active turn. Already completed work remains.':action==='create_chat'?'Create an empty conversation and organize it in this project locally. Send its first message afterward.':'Review this request before applying it.';
 if(action!=='create_project')$('manageExplanation').textContent+=' Project: '+(management.projects.find(p=>p.id===project)?.name||project)+'.'+(thread?' Chat: '+(management.threads.find(t=>t.id===thread)?.title||thread)+'.':'')+(pendingManagement.turn_id&&action.includes('turn')?' Turn: '+pendingManagement.turn_id+'.':'');
 $('manageNameLabel').hidden=!['create_project','rename_project','create_chat','rename_chat'].includes(action);$('manageInputLabel').hidden=action!=='steer_turn';
 $('manageName').value=seed.name||seed.title||'';$('manageInput').value=seed.input||'';$('manageInputLabel').firstChild.textContent=action==='steer_turn'?'Steering message':'First message';
 $('manageName').required=!$('manageNameLabel').hidden;$('manageInput').required=!$('manageInputLabel').hidden;
 $('manageError').textContent='';$('manageConfirm').disabled=false;dialog.showModal();($('manageNameLabel').hidden?$('manageInput'):$('manageName')).focus();
}
for(const [id,action] of [['createProject','create_project'],['renameProject','rename_project'],['createChat','create_chat'],['renameChat','rename_chat'],['cancelTurn','cancel_turn'],['steerTurn','steer_turn']])$(id).onclick=()=>{try{review(action);}catch(e){notice(e.message,'error');}};
$('showClosed').onclick=async()=>{management.closed=!management.closed;$('showClosed').textContent=management.closed?'Show open':'Show closed';try{await loadThreads();}catch(e){notice(e.message,'error');}};
$('closeChat').onclick=()=>{try{review(management.closed?'restore_chat':'close_chat');}catch(e){notice(e.message,'error');}};
const actions={create_project:'/api/projects/create',rename_project:'/api/projects/update',create_chat:'/api/threads/create',rename_chat:'/api/threads/update',close_chat:'/api/threads/close',restore_chat:'/api/threads/restore',cancel_turn:'/api/turns/cancel',steer_turn:'/api/turns/steer'};
$('manageForm').onsubmit=async e=>{e.preventDefault();if(management.busy||management.uncertain||!pendingManagement)return;const request={...pendingManagement,name:$('manageName').value.trim(),title:$('manageName').value.trim(),input:$('manageInput').value.trim(),text:$('manageInput').value.trim()};management.busy=true;$('manageConfirm').disabled=true;updateManagement();try{const payload={};if(request.action==='create_project'){payload.name=request.name;payload.idempotency_key=request.idempotency_key;}else if(request.action==='rename_project'){payload.project_id=request.project_id;payload.name=request.name;}else if(request.action==='create_chat'){payload.project_id=request.project_id;payload.title=request.title;payload.idempotency_key=request.idempotency_key;}else if(request.action==='rename_chat'){payload.thread_id=request.thread_id;payload.title=request.title;}else if(['close_chat','restore_chat'].includes(request.action)){payload.thread_id=request.thread_id;}else{payload.thread_id=request.thread_id;payload.turn_id=request.turn_id;payload.idempotency_key=request.idempotency_key;if(request.action==='steer_turn')payload.text=request.text;}const result=await api(actions[request.action],payload);dialog.close();if(['create_project','create_chat','restore_chat'].includes(request.action)){management.closed=false;$('showClosed').textContent='Show closed';}await refresh();const selected=result.thread_id||result.agent_id;if(result.project_id){state.project=result.project_id;$('projects').value=state.project;}if(selected){selectMode('agent');state.thread=selected;state.agentThread=selected;await loadMessages(selected);startPolling();}await loadThreads();notice(result.message||(result.metadata_scope==='local_companion'?'Saved in this companion. Chat messages and agent runs still use your Nanocodex account.':request.action==='cancel_turn'?'Stop requested. Status will update when the server confirms.':'Request accepted.'),'success');}catch(err){management.uncertain=true;$('manageError').textContent=err.message+' Refresh the workspace to check the outcome before starting another request.';}finally{management.busy=false;updateManagement();}};
async function refreshActivity(thread){if(state.thread!==thread)return;try{const detail=await api('/api/thread?thread_id='+encodeURIComponent(thread));if(state.thread!==thread)return;management.details=detail.state||detail;const active=Array.isArray(management.details.active_turns)?management.details.active_turns:[];$('activityLabel').textContent=management.details.status|| (active.length?'Running · '+active.length+' active turn(s)':'Ready');$('cancelTurn').hidden=!active.length;$('steerTurn').hidden=!active.length;}catch(e){if(state.thread===thread){management.details=null;$('activityLabel').textContent='Status unavailable';$('cancelTurn').hidden=true;$('steerTurn').hidden=true;}}}
$('copyWorkspace').onclick=async()=>{try{const projects=management.projects;const rows=['ncw1'];for(const project of projects){rows.push(['P',project.id,project.name||'Untitled project'].map((v,i)=>i?encodeURIComponent(String(v).replace(/[\x00-\x1f\x7f]/g,' ')):v).join('\t'));const result=await api('/api/threads?project_id='+encodeURIComponent(project.id)+'&closed=false');for(const t of result.threads||[])rows.push(['T',project.id,t.id,t.title||'Untitled chat',t.status||'unknown'].map((v,i)=>i?encodeURIComponent(String(v).replace(/[\x00-\x1f\x7f]/g,' ')):v).join('\t'));}const snapshot=rows.join('\n');if(rows.length>1001||new TextEncoder().encode(snapshot).length>262144)throw Error('Workspace exceeds the addon snapshot limit (1000 rows / 256 KiB).');await navigator.clipboard.writeText(snapshot);notice('Workspace copied. In WoW, use /nc projects and Paste workspace. This is a snapshot; copy again to refresh.','success');}catch(e){notice(e.message,'error');}};
const coreImport=$('import').onclick;$('import').onclick=async()=>{let raw;try{raw=JSON.parse($('importContext').value);}catch{return coreImport();}if(!['nanocodex.ask','nanocodex.action'].includes(raw.type)||raw.mode!=='agent'&&raw.type!=='nanocodex.action')return coreImport();try{if(!state.connected)throw Error('Connect your account before importing a project request.');await refresh();if(raw.project_id&&!management.projects.some(p=>p.id===raw.project_id))throw Error('This project is not in the current account. Refresh the WoW workspace snapshot.');if(raw.project_id){state.project=raw.project_id;$('projects').value=raw.project_id;await loadThreads();}if(raw.thread_id&&!management.threads.some(t=>t.id===raw.thread_id))throw Error('This chat is not in the selected project. Refresh the snapshot.');if(raw.type==='nanocodex.action'){review(raw.action,raw);return;}selectMode('agent');state.thread=raw.thread_id||null;state.agentThread=state.thread;if(state.thread)await loadMessages(state.thread);state.context=raw.context||{};$('prompt').value=String(raw.prompt||'');saveDraft();notice('WoW project request imported. Review the selected chat and press Send.');}catch(e){notice(e.message,'error');}};
$('prompt').addEventListener('paste',event=>{try{const raw=JSON.parse(event.clipboardData.getData('text/plain'));if(raw.type!=='nanocodex.action')return;event.preventDefault();$('importContext').value=JSON.stringify(raw);$('import').click();}catch{}});
restoreDraft();updateManagement();

const historyPages=new Map();
function rememberHistory(path,result){
 const query=new URL(path,location.origin).searchParams,id=query.get('thread_id');if(!Array.isArray(result.message_details))return;
 const page=historyPages.get(id)||{rows:new Map(),before:null,more:false};
 for(const m of result.message_details)page.rows.set(String(m.cursor),m);
 if(page.before===null||query.has('before')){page.before=result.first_cursor;page.more=!!result.has_more;}
 historyPages.set(id,page);
}
function renderHistory(id){
 if(state.thread!==id)return;const page=historyPages.get(id);if(!page){$('loadEarlier').hidden=true;return;}
 const compare=(a,b)=>a.length-b.length||a.localeCompare(b);let rows=[...page.rows.values()].sort((a,b)=>compare(String(a.cursor),String(b.cursor)));
 const completed=new Set(rows.filter(m=>m.role==='assistant'&&m.event_type==='turn_completed').map(m=>m.turn_id));
 rows=rows.filter(m=>m.role!=='assistant'||!completed.has(m.turn_id)||m.event_type==='turn_completed');
 $('messages').replaceChildren();for(const m of rows)appendMessage(m.role,m.text);$('loadEarlier').hidden=!page.more||!page.before;
}
$('loadEarlier').onclick=async()=>{const id=state.thread,page=historyPages.get(id);if(!id||!page?.before)return;$('loadEarlier').disabled=true;try{await api('/api/messages?thread_id='+encodeURIComponent(id)+'&before='+encodeURIComponent(page.before));renderHistory(id);}catch(e){notice(e.message,'error');}finally{$('loadEarlier').disabled=false;}};
